version: '3.8'

services:
  agentic-rag:
    build: .
    container_name: agentic-rag-app
    environment:
      # These should be set in your .env file or passed as environment variables
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      # Mount data directories for persistence
      - ./data:/app/data
      - ./output:/app/output
      - ./config:/app/config
      # Mount .env file if it exists
      - ./.env:/app/.env:ro
    working_dir: /app
    stdin_open: true
    tty: true
    restart: unless-stopped
    # Uncomment the following lines if you want to expose a web interface in the future
    # ports:
    #   - "8000:8000"

  # Optional: Development service with volume mounts for live code changes
  agentic-rag-dev:
    build: .
    container_name: agentic-rag-dev
    environment:
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      # Mount the entire source code for development
      - ./src:/app/src
      - ./utils:/app/utils
      - ./main.py:/app/main.py
      - ./config:/app/config
      - ./data:/app/data
      - ./output:/app/output
      - ./.env:/app/.env:ro
    working_dir: /app
    stdin_open: true
    tty: true
    profiles:
      - dev
    command: ["python", "main.py"]
