# Directory Names
data_dir: "data"
output_dir: "output"
model_dir: "models"
dataset_kaggle: "Cornell-University/arxiv"
embedding_cache_dir: "embedding_cache"

# File Names
env_file: ".env"
dl_file_name: "arxiv-metadata-oai-snapshot.json"
filter_file_name: "filtered_abstracts.pkl"
chunk_file_name: "chunked_abstracts.pkl"
chunk_selected_file_name: "chunks_selected.pkl"
embeddings_file_name: "embeddings_final.npy"
embeddings_selected_file_name: "embeddings_selected.npy"
prompt_file_name: "prompts.txt"

# Output file names
base_graph_file_name: "base_rag_graph.png"
fine_tuned_graph_file_name: "fine_tuned_rag_graph.png"
multi_run_file_name: "multi_run_results.txt"
unit_test_file_name: "unit_test_results.txt"

# Filtering Variables
date: "2021-10-01"

# Chunking Variables
chunk_size: 2000
chunk_overlap: 200
min_text_len: 50

# Embedding Variables
fast_embed_name: "BAAI/bge-small-en-v1.5"
ch_batch_size: 256
save_every: 40000
save_checkpoints: False

# Upserting Variables
pc_index: "abstract-index"
pc_index_selected: "abstract-index-selected"
distance_metric: "cosine"
pc_batch_size: 500
pc_cloud: "aws"
pc_region: "us-east-1"

# RAG Variables
gemini_model_name: "gemini-2.0-flash"
top_k: 10

# Simplification Model Configuration
simplification_model:
  use_finetuned: true
  base_model_name: "HuggingFaceTB/SmolLM2-1.7B-Instruct"
  model_path: "models/"
  generation_params:
    max_length: 1000
    temperature: 0.7
    do_sample: true
    top_p: 0.9
    pad_token_id: 2  # SmolLM2 EOS token


classification_prompt: |
  You are a query classifier. Your task is to determine if a user's query requires searching for recent scientific papers (from 2022-2024).

  Analyze the following query: "{query}"

  Based on the query's intent, decide if a search is needed.

  Answer YES if the query's intent matches any of these principles:
  - **Recency-focused**: It explicitly asks for recent, current, latest, or state-of-the-art information (e.g., "latest developments," "recent breakthroughs," "most recent").
  - **Evolving Topics**: It is about a rapidly advancing field where new findings are constant (e.g., generative AI, LLM fine-tuning, CRISPR gene editing, COVID-19 research).
  - **Modern Comparison**: It asks how a topic has changed or evolved into the modern era (e.g., "how has X improved since 2021?").

  Answer NO if the query's intent matches any of these principles:
  - **Historical**: It is historical, asking about origins, discoveries, or foundational concepts from the past.
  - **Fundamental**: It asks for a basic definition or a well-established principle that is unlikely to have changed recently (e.g., "what is gravity?").

  If the intent is ambiguous or does not clearly fit the YES criteria, default to NO.

  Respond with the word YES/NO followed by a brief explanation of your reasoning in the following format:
  YES/NO - [brief explanation]

rewrite_prompt: |
  You are an expert researcher skilled at creating focused and accurate queries for scientific document retrieval.

  Given the following user query, generate an enhanced query passage that includes relevant general technical terminology and concepts to improve retrieval.

  User Query: "{query}"

  The enhanced query should:
  - Be approximately 150-200 words long
  - Use clear and accurate scientific language without unnecessary jargon
  - Capture core concepts, methodologies, and key themes related to the subject
  - Avoid overly narrow or highly specialized terms
  - Emphasize terminology that would appear broadly in scientific literature related to the topic

  Output the enhanced query passage only, without additional explanations or context.

simplify_prompt: |
  You are an expert science communicator. Your task is to explain the following technical abstract to an intelligent, non-expert audience (e.g., an undergraduate student or a professional from an adjacent field).

  Explain this abstract: {abstract}

  Your explanation must follow these rules:
  1.  **Start with the Core Idea:** Begin with a high-level summary of the paper's primary goal and its main finding.
  2.  **Define as You Go:** Clearly define essential technical terms and jargon the first time they appear.
  3.  **Preserve Accuracy:** Maintain all key concepts and their relationships from the original text without oversimplifying to the point of being incorrect.
  4.  **Use Accessible Language:** Use clear language and helpful analogies where appropriate, but do not sacrifice technical accuracy.
  5.  **Maintain Logical Flow:** Structure the explanation logically, moving from the background and problem to the methods and conclusion.


final_prompt: |
  You are a research analyst. Your task is to synthesize the provided context to answer the user's query.

  Original User Query: "{query}"

  Enhanced Query Perspective:
  {rewrite}

  Context from Retrieved Papers (includes title, year, and abstract):
  {context}

  Your instructions:
  1.  **Synthesize, Don't Just List**: Do not summarize each paper individually. Integrate the findings from all provided abstracts into a single, cohesive paragraph.
  2.  **Prioritize Recency**: The context includes the publication year for each paper. You MUST give more weight to the findings from the most recent papers. If findings conflict, mention that newer research suggests a different conclusion.
  3.  **Address the Core Question**: Your entire response should focus on directly answering the original user query. Use the enhanced perspective to ensure a comprehensive answer.
  4.  **Identify Consensus**: Your synthesis should highlight the core findings or conclusions that are consistent across multiple papers.

  Generate a single, dense paragraph as the final answer.


